server:
  port: 8090
spring:
  application:
    name: yd-service-autodeliver

yd-service-resume:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整
    ## 当访问到故障请求的时候，它会再尝试访问⼀次当前实例（次数由MaxAutoRetries配置），
    ## 如果不⾏，就换⼀个实例进⾏访问，如果还不⾏，再换⼀次实例访问（更换次数由MaxAutoRetriesNextServer配置），
    ## 如果依然不⾏，返回失败信息。
    #请求连接超时时间
    ConnectTimeout: 5000
    #请求处理超时时间
    ReadTimeout: 5000
    #对所有操作都进⾏重试
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 0 #对当前选中实例重试次数，不包括第⼀次调⽤
    MaxAutoRetriesNextServer: 0 #切换实例的重试次数

## 开启Feign的熔断功能
feign:
  hystrix:
    enabled: false
  sentinel:
    enabled: true

logging:
  level:
    com.jxsj.feign.ResumeFeignClient: debug

